### ISSUE TITLE
**Implementar cadastro de locações**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#10]
[RF01] O  sistema  deve  registrar  locações,  indicando  o  cliente  e  os itens locados, bem como a data e o valor da locação e a data de devolução prevista de cada item.

- [x] Elaborar testes unitários
- [x] Elaborar testes de aceitação
- [x] Criar interface para cadastrar locação
- [x] Criar classes de modelo
- [x] Criar método para efetivar locação

**Comment by estrazulas** [comment]
liberado no deploy
