### ISSUE TITLE
**Implementação da reserva de itens**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#12]
[RF04] O sistema deve registrar a reserva de filmes a clientes permitindo indicar, ainda, o tipo de mídia desejado;

- [x]  Elaborar testes unitários
- [x]  Elaborar testes de aceitação
- [x]  Criar classes de modelo 
- [x]  Criar classes de controler
- [x]  Criar métodos para reserva

**Comment by estrazulas** [comment]
liberado no deploy
