### ISSUE TITLE
**Documentar Revisão individual**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#15]
Lições aprendidas do ponto de vista individual dos membros do time em relação a execução do projeto em si.

**Comment by estrazulas** [comment]
Com relação aos acertos do projeto, a decisão de optar por uma ferramenta para facilitar a geração das entidades e cadastros permitiu que a equipe conseguisse entregar rapidamente os principais cadastros necessários para manutenção da video locadora imperial. Ganhamos principalmente com relação aos testes unitários e testes de aceitação pois toda a estrutura do jhipster já vinha com as configurações necessárias e inclusive vários testes da api já implementados.

Com relação ao nossos erros de projeto, em muitos casos acabamos tendo que regerar a aplicação pois fizemos a liberação em partes das entidades, tendo que regerar a aplicação várias vezes, gerando vários branchs durante o projeto, pois uma vez que precisávamos mudar algum relacionamento ou campo tinhamos problemas de sobrescritas das classes já modificadas, e isto acabou gerando um certo retrabalho. 

Algumas tecnologias como uso de mysql com heroku e outh tiveram que ser refeitas, e por dificuldades no desenvolvimento acabamos optando por trocar de tecnologia.

Com relação às iterações que tivemos acabamos tendo que aumentar os prazos de entrega, pois foram surgindo situações inesperadas durante a customização no jhipster que tivemos que estudar para poder implementar, uma vez que a equipe de desenvolvimento desconhecia de várias tecnologias utilizadas pelo jhipster.
