### ISSUE TITLE
**Revisão do projeto**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#16]
Descrição do processo de desenvolvimento, principais problemas e tomadas de decisão em relação ao projeto. Atribuição das atividades e técnicas de gerenciamento, monitoramento e controle.

**Comment by EliandroMinski** [comment]
# VIDEOLOCADORA IMPERIAL
<p> </p>
<p><strong>Revisão do Projeto</strong></p>
<p><strong>Planejamento</strong></p>

Após reunião inicial, com a equipe do projeto, com foco no planejamento do projeto, ficou definido que a Extreme Programming (XP) será a metodologia ágil de desenvolvimento utilizada. As interações  realizadas com um intervalo de cinco (5) dias em média, onde, a cada intervalo, será entregue as tarefas/issues, já cadastradas no GitHub e com suas respectivas capacidades definidas. As definições das capacidades, foram baseadas na sequência de Fibonacci (1,2,3,5,8) com pontuação máxima de 8 pontos.
O desenvolvimento será feito através da prática da programação em pares, ficando a cargo desta atividade os desenvolvedores Samuel e Daniel.
Inicialmente foram cadastradas no GitHub, 32 tarefas/issues, pré definidas dos tipos: Arquitetural, Documental e Testes/Desenvolvimento, para cada uma dessas tarefas, já ficou estabelecida sua “Complexidade”, “Pontuação” e “Prioridade”, bem como o responsável pela mesma. Esse número de tarefas/issues poderá sofrer alterações no decorrer do desenvolvimento do projeto.
A gerência do projeto, ficará a cargo de Eliandro Luiz Minski, decisão essa tomada após reunião entre os membros da equipe. Portanto, o mesmo será o responsável pela comunicação entre cliente e equipe do projeto, mediando as interações; acompanhamento das atividades para que a entrega das tarefas estejam dentro do prazo estabelecido e supervisão dos demais membros da equipe.
Ficou definido que os seguintes módulo serão implementados: Cadastro de Clientes e colaboradores; Cadastro de Midia; Locação de Item; Devolução de Item; Reserva de Item.

<p><strong>Iterações</strong></p>
<table>
<thead>
<tr>
<th>ID</th>
<th>Início da Interação</th>
<th>Término da Interação</th>
<th>Ações</th>
</tr>
</thead>
<tbody>
<tr>
<td>01</td>
<td>01/12/2018</td>
<td>05/12/2018</td>
<td>Configurado Heroku (Java e Mysql) - Daniel;  

Configurado Arquitetura Inicial Spring Boot – Samuel;  
Criado Readme no GitHub – Eliandro;  
Criado Base de Dados – Samuel e Daniel;  
Criado Arquivo Postmortem – Eliandro.  
</td>
</tbody>
<tbody>
<tr>
<td>02</td>
<td>05/12/2018</td>
<td>10/12/2018</td>
<td>
Implementado Controle de Autenticação de Usuários Oauth2 – Daniel e Samuel;  

Implementado CRUD Clientes – Daniel;Criado documento os Principais Casos de Uso (Locação, Devolução e Reservas) - Eliandro;
Implementado CRUD de Cadastro de Filmes novos – Samuel;
Criado arquivo Post Mortem – Eliandro.
</td>
</tbody>
<tbody>
<tr>
<td>03</td>
<td>10/12/2018</td>
<td>12/01/2019</td>
<td>
Implementado CRUD – Item de filmes - Daniel;  

Implementado Inativação de dependentes do titular - Samuel e Daniel;
Implementado Funcionalidade para desativar/ativar clientes - Samuel.
Criado arquivo Post Mortem - Eliandro;
</td>
</tbody>
<tbody>
<tr>
<td>04</td>
<td>16/01/2019</td>
<td>24/01/2019</td>
<td>Consulta de Acervo – Samuel e Daniel;

Documentado visão de uso da solução – Eliandro;
Estudado filters jhipster – Samuel e Daniel;
Estudado como implementar telas novas(frontend) Samuel e Daniel;
Criado arquivo Post mortem iteração 4 – Eliandro, Samuel e Daniel;
Implementado Inativação de dependentes do titular – Samuel e Daniel.

</td>
</tbody>
<tbody>
<tr>
<td>05</td>
<td>24/01/2019</td>
<td>02/02/2019</td>
<td>Implementar cadastro de locações - Daniel;

Implementado reserva de itens - Samuel;
Documentado visão de implantação - Eliandro, Daniel, Eliandro; 
Documentado funcionalidades e diferenciais - Daniel;
Criado arquivo Post mortem. - Eliandro.
</td>
</tbody>
<tbody>
<tr>
<td>06</td>
<td>02/02/2019</td>
<td>18/02/2019</td>
<td>Compilar relatório final do projeto - Eliandro, Daniel, Samuel;  

Documentar Postmortem da iteração - Eliandro;
Documentar Gerência de Configuração e Ambiente - Daniel;
Documentação/Medição dos atributos de qualidade da aplicação - Samuel;
Documentar Revisão individual -Daniel, Samuel, Eliandro;
Validação de reserva com item disponível - Samuel;
Cancelamento de Reservas - Daniel;
Controle de exclusão de clientes com locações - Daniel, Samuel.
</td>
</tbody>
</table>
<p> </p>
<p><strong>Atividades não concluídas</strong></p>

As seguintes atividades não foram concluídas:

 * Implementar registro de devoluções;
 * Prioridade de reserva;
 * Controle de exclusão de clientes com locações;
 * Cancelamento de reserva;
 * Bloqueio de cliente com atraso;
 * Validar data de devolução superior a data de locação;
 * Controlar prazo de devolução catálogo/lançamento;
 * Validação de reserva com item disponível.

<p><strong>Desenvolvimento, monitoramento e Controle</strong></p>

O processo de desenvolvimento seguiu com o uso da metodologia ágil XP, onde os desenvolvedores realizaram as implementações em pares, quando um programador estava codificando o outro atuava como observador, ocorreu também a troca do papel de observador e do codificador durante o andamento das iterações.
Para controle das modificações e monitoramento das atividades utilizamos a ferramenta de controle de versão github e o seu dashboard disponível para gerenciamento de projetos.
Ao total foram realizados 90 commits e criados 13 branchs nas 6 iterações realizadas para este projeto. Das tarefas planejadas e selecionadas inicialmente, 29 foram concluídas e 10 ficaram em aberto.
Tivemos alguns problemas no desenvolvimento da aplicação conforme estão relatados nos cards do github, dentre os quais, destacam-se:
Problema com MySql e Heroku:
O MySql com Heroku não funcionou de forma adequada, ocorrendo erros quando necessitamos aumentar as entidades. Os plugins disponíveis eram pagos, sendo assim migramos para o PostgreSql.
Problemas com autenticação Oauth do Google:
A ideia inicial era utilizar a autenticação de terceiros, chegamos a implementar, porém com essa autenticação perdemos muitos recursos administrativos que o próprio jhipster traz como logs e métricas. Sendo que não fazia parte dos requisitos iniciais do cliente, optamos por re-fazer com controle de autenticação própria utilizando Spring Security.
Problemas com alteração de entidades com Jhipster:
O Jhipster facilitou a criação dos cruds, porém quando um relacionamento ou atributo estava incorreto, era necessário realizar uma nova geração de todas as classes. Assim perdiamos as regras de negócios implementadas anteriormente. Como solução de contorno, quando necessário re-gerar as entidades, utilizava-mos outro branch com merge manual e analise dos commits para evitar problemas.

<p><strong>Conclusão</strong></p>

O projeto Vídeo Locadora Imperial, foi concluído dentro do prazo determinado, as principais atividades planejadas em cada sprint foram implementadas conforme cronograma inicial, as que não foi possível concluir, foram devidamente justificadas na documentação do projeto. Todas as dificuldades enfrentadas no decorrer do desenvolvimento do projeto, foram corrigidas através da busca por novos conhecimentos e a substituição das ferramentas que estavam apresentando instabilidade ou conflitos. A documentação refente ao projeto foi toda elaborada, revisada e publicada. A aplicação encontra-se em funcionalidade, conforme links publicados nos demais documentos do projeto.
