### ISSUE TITLE
**Documentar visão de uso da solucão**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#17]
Guia de uso da solução do ponto de vista de todos os stakeholders identificados.

**Comment by EliandroMinski** [comment]
![new mockup 1](https://user-images.githubusercontent.com/45404618/50871706-a88e3600-13a3-11e9-8c6a-e0bb434cf538.png)
![new mockup 1 copy](https://user-images.githubusercontent.com/45404618/50871718-b348cb00-13a3-11e9-872d-ea4ee76e5906.png)
![new mockup 1 copy 2](https://user-images.githubusercontent.com/45404618/50871726-bc399c80-13a3-11e9-8bc6-5d9f4b0c54c5.png)
![new mockup 1 copy 3](https://user-images.githubusercontent.com/45404618/50871733-bfcd2380-13a3-11e9-98c1-39ff983d4b8e.png)
![new mockup 1 copy 4](https://user-images.githubusercontent.com/45404618/50871739-c2c81400-13a3-11e9-9a57-a260bdf20c1c.png)
