### ISSUE TITLE
**Documentar visão de implantação**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#18]
Visão e instruções de implantação do sistema. Um release notes com os erros, falhas e faltas conhecidos também é bem visto. Site onde ele está implantado e/ou um vídeo de demonstração promovendo o produto (pode estar no youtube ou outro serviço semelhante).

**Comment by estrazulas** [comment]
**Visão e instruções de implantação do sistema**

Esta seção tem por objetivo fornecer as informações mínimas necessárias para implantação e utilização do software vlimperial.

Para implantação é necessário que o servidor ou plataforma de serviço possua recursos para trabalhar com **PostgreSQL**,  **Java 8(mínimo)**  e em caso de necessidade de alta demanda sobre as consultas do sistema também é possível a utilização de um serviço **Elasticsearch**.

** Release Notes **

A atual versão do software é v28.  Atualmente está hospedada no heroku, onde utiliza add-ons gratuitos para suporte ao Bonsai Elasticsearch e Heroku Postgres.

** Erros , falhas e faltas conhecidas **

- O uso do recurso de elasticsearch supera o máximo de shards disponível pelo dyno gratuito utilizado, fazendo com que as consultas possam não funcionar, seria necessário a migração para um plano que suporte as consultas sobre as entidades do sistema. 

- Em alguns casos a aplicação não sobe pela limitação de uso dos indices no elastic search, sendo necessário acessar o dashboard do bonsai elasticsearch e manualmente remover os shards utilizados e reiniciar a aplicação.

- Atualmente a aplicação não disponibiliza recursos de controle de pagamento das reservas, ficando a cargo do atendente manualmente fazer o controle da cobrança.

- Alguns campos possuem limitação de tamanho da string, podendo gerar um erro não tratado "bad request" ao tentar salvar.
