### ISSUE TITLE
**Documentar principais casos de uso**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#21]
- [ ] Caso de uso de locação
- [ ] Caso de uso de reserva
- [ ] Caso de uso de devolução

**Comment by EliandroMinski** [comment]
![logo](https://user-images.githubusercontent.com/45404618/49707767-f3395880-fc13-11e8-9029-e1eea094f181.jpg)
# Empresa: Videolocadora Imperial Ltda.  
<h1><strong>CASOS DE USO</strong></h1>

Versão | Data | Nome
-- | -- | --
1.0 | 06/12/2018 | Eliandro 			Minski  


<strong>Equipe de Elaboração: </strong>Daniel Servero Estrazulas, Samuel Bristot Loli, Eliandro Luiz Minski.  

### Sumário


        
	
  1.1 – Descrição.

	1.2 – Atores.
	
	1.3 – Pré-condições.

	1.4 – Principais Eventos.

	1.5 – Eventos Alternativos.

	1.6 – Pós Condições

	1.7 – Requisitos Especiais.

2 – Casos de Uso de Devolução.

	2.1 – Descrição.

	2.2 – Atores.
	
	2.3 – Pré-condições.

	2.4 – Principais Eventos.

	2.5 – Eventos Alternativos.

	2.6 – Pós Condições

	2.7 – Requisitos Especiais.	


3 – Casos de Uso de Reserva.

	3.1 – Descrição.

	3.2 – Atores.
	
	3.3 – Pré-condições.

	3.4 – Principais Eventos.

	3.5 – Eventos Alternativos.

	3.6 – Pós Condições

	3.7 – Requisitos Especiais.	

1 – Casos de Uso de Locação.

	1.1 – Descrição.

    • Neste caso, será descrito como é realizado a locação de mídias.
      

	1.2 – Atores.

    • Atendente.
      
	
	1.3 – Pré-condições.

    • O atendente já deve possuir cadastro no sistema, com permissões de acesso ao modulo “Locação”.


	1.4 – Principais Eventos.

    • O atendente realiza o login no sistema e acessa o modulo “Locação”;
    • Digita o código ou nome do cliente para iniciar o processo de seleção das mídias que serão locadas;
    • Com o cliente já selecionado, o atendente digita o código da(s) mídia(s) escolhida(s) pelo mesmo;
    • O sistema informa o prazo de devolução de cada mídia escolhida e o respectivo valor;
    • Após a(s) mídia(s) ser(em) informada(s), o atendente fecha a locação, imprimindo um comprovante, em duas vias, uma via fica na locadora e a outra com o cliente. Neste comprovante, constam o código e nome do cliente, das mídias locadas, data de locação e devolução e o valor a ser pago;
    • O atendente realiza a cobrança do valor das diárias das referidas mídias locadas. 
      
      
	1.5 – Eventos Alternativos.

    • Atendente não cadastrado ou sem permissão de acesso ao modulo “Locação”;
    • Cliente sem cadastro ou bloqueado;
    • O atendente pode alterar a data de devolução, conforme solicitação do cliente, neste caso o sistema calcula novos valores de diárias.
      

	1.6 – Pós Condições.

    • Se todos os campos forem preenchidos corretamente e a locação for realizada com sucesso, o sistema atribui a(s) mídia(s) locada(s) o status de “não disponível”, informando a data em que a(s) mesma(s) deve(m) retornar a locadora.
    • O sistema informa ao modulo “Financeiro” o valor recebido ou a receber por locação realizada.
    • Após o encerramento de cada locação, o sistema volta o ponto inicial do modulo “Locação”.
      

	1.7 – Requisitos Especiais.

    • O sistema deve trazer a informação do limite de mídias disponíveis por cliente e se o pagamento deve ser realizado no ato da locação ou na devolução;
    • Alguns clientes podem possuir “Bônus” ou “Descontos” em locações, essa informação será disponibilizada pelo sistema no ato de fechamento da locação, ficando de responsabilidade ao atendente preencher o campo “bônus”, com o valor do respectivo desconto.
