### ISSUE TITLE
**Criar readme no github**

### ISSUE THREAD

**Issue by MprofSC** [MprofSC/videolocadoraimperial#3]
Página de readme/inicial com nome do projeto, justificativa do projeto, descrição do produto, especificação do papel de cada membro da equipe (com informações de contato como email) e demais informações que o time achar pertinentes.

**Comment by EliandroMinski** [comment]
[Imperial.Locadora.-.README.pdf](https://github.com/MprofSC/videolocadoraimperial/files/2640321/Imperial.Locadora.-.README.pdf)

**Comment by EliandroMinski** [comment]
[README -1.0.pdf](https://github.com/MprofSC/videolocadoraimperial/files/2645059/README.-1.0.pdf)
