### ISSUE TITLE
**Documentar postmortem do projeto**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#31]
Resumo do que funcionou e do que não funcionou durante a execução do projeto, e planos para melhorar o que não funcionou, lições aprendidas, etc. Período: data de início - data de término da iteração.

- [ ] O que estava planejado? atividades e pra quem
- [ ] O que foi feito? atividades e por quem
- [ ] O que não foi feito? atividades e por quem, quais os impedimentos
- [ ] O que está planejado para a próxima iteração? atividades e pra quem
- [ ] Lições aprendidas (Post Mortem / Rationale)

**Comment by EliandroMinski** [comment]
# VIDEOLOCADORA IMPERIAL
<p> </p>
<p><strong>Postmortem</strong></p>
<table>
<thead>
<tr>
<th>Início da Interação</th>
<th>Término da Interação</th>
</tr>
</thead>
<tbody>
<tr>
<td>02/02/2019</td>
<td>18/02/2019</td>
</tbody>
</table>
<p> </p>
<p><strong>O Que Foi Planejado</strong></p>

Compilar relatório final do projeto;
Documentar Postmortem da iteração;
Documentar Gerência de Configuração e Ambiente;
Documentação/Medição dos atributos de qualidade da aplicação;
Documentar Revisão individual;
Validação de reserva com item disponível;
Cancelamento de Reservas;
Controle de exclusão de clientes com locações.


<p><strong>O Que Foi Feito</strong></p>

Compilar relatório final do projeto - Eliandro, Samuel e Daniel;
Documentar Postmortem da iteração - Eliandro;
Documentar Gerência de Configuração e Ambiente - Samuel, Daniel;
Documentação/Medição dos atributos de qualidade da aplicação - Daniel;
Documentar Revisão individual - Daniel, Samuel, Eliandro;  

<p><strong>O Que Não Foi Feito:</strong></p>

Cancelamento de Reservas;
Controle de exclusão de clientes com locações.
Validação de reserva com item disponível
