### ISSUE TITLE
**Post Mortem - Iteração**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#33]
Resumo do que funcionou e do que não funcionou durante a execução da iteração, e planos para melhorar o que não funcionou, lições aprendidas, etc. 

Período: 01/12 - 05/12

O que estava planejado? atividades e pra quem
O que foi feito? atividades e por quem
O que não foi feito? atividades e por quem, quais os impedimentos
O que está planejado para a próxima iteração? atividades e pra quem
Lições aprendidas (Post Mortem / Rationale)

**Comment by EliandroMinski** [comment]
# VIDEOLOCADORA IMPERIAL
<p> </p>
<p><strong>Postmortem</strong></p>
<table>
<thead>
<tr>
<th>Início da Interação</th>
<th>Término da Interação</th>
</tr>
</thead>
<tbody>
<tr>
<td>01/12/2018</td>
<td>05/12/2018</td>
</tbody>
</table>
<p> </p>
<p><strong>O Que Foi Planejado</strong></p>
Configurar Heroku (Java e Mysql);   

Configurar Arquitetura Inicial Spring Boot;
Criar Readme no GitHub;
Criar Base de Dados;
Criar Arquivo Postmortem.
<p><strong>O Que Foi Feito</strong></p>
Configurarado Heroku (Java e Mysql) - Daniel;  

Configurarado  Arquitetura Inicial Spring Boot - Samuel;
Criar Readme no GitHub - Eliandro;
Criar Base de Dados - ????;
Criar Arquivo Postmortem - Eliandro.
<p><strong>O Que Não Foi Feito</strong></p>
<p> Todas as atividades planejadas foram realizadas.</p>
<p><strong>Planejado Para a Próxima Interação</strong></p>
<p> ???? </p>
<p><strong>Lições Aprendidas</strong></p>
<p> Algumas atividades planejadas, sofreram alterações do ponto de vista de metodologia aplicada, como por exemplo a criação de um branch para cada issue, para posteriormente realizar o merge com o master, fato esse motivado  pelo início do desenvolvimento antes desta definição de realizar o processo de versionamento e deploy. Para as próximas issues de codificação planeja-se seguir a metodologia de realizar o  fechamento da issue  por meio de branch e request para merge no master,  após a realização dos testes.
