### ISSUE TITLE
**Post Mortem - Interação 2**

### ISSUE THREAD

**Issue by estrazulas** [MprofSC/videolocadoraimperial#37]
Resumo do que funcionou e do que não funcionou durante a execução da iteração, e planos para melhorar o que não funcionou, lições aprendidas, etc. 

Período: 05/12 - 10/12

- [ ] O que estava planejado? atividades e pra quem
- [ ] O que foi feito? atividades e por quem
- [ ] O que não foi feito? atividades e por quem, quais os impedimentos
- [ ] O que está planejado para a próxima iteração? atividades e pra quem
- [ ] Lições aprendidas (Post Mortem / Rationale)

**Comment by EliandroMinski** [comment]
# VIDEOLOCADORA IMPERIAL
<p> </p>
<p><strong>Postmortem</strong></p>
<table>
<thead>
<tr>
<th>Início da Interação</th>
<th>Término da Interação</th>
</tr>
</thead>
<tbody>
<tr>
<td>06/12/2018</td>
<td>10/12/2018</td>
</tbody>
</table>
<p> </p>
<p><strong>O Que Foi Planejado</strong></p>
Implementar Controle de Autenticação de Usuários Oauth2;
Implementar CRUD Clientes;
Documentar Principais Casos de Uso;
Implementar CRUD de Cadastro de Filmes novos;
Criar arquivo Post Mortem.

<p><strong>O Que Foi Feito</strong></p>

Implementado Controle de Autenticação de Usuários Oauth2 - Daniel e Samuel;
Implementado CRUD Clientes - Daniel;
Criado documento os Principais Casos de Uso (Locação, Devolução e Reservas) - Eliandro;
Implementado CRUD de Cadastro de Filmes novos - Samuel;
Criado arquivo Post Mortem - Eliandro.

<p><strong>O Que Não Foi Feito</strong></p>
<p> Não foi realizado a atividade de validação de campos de data, CPF e dependentes.</p>
<p><strong>Planejado Para a Próxima Interação</strong></p>

Implementar CRUD - Item de filmes;

Inativação de dependentes do titular ;
Funcionalidade para desativar/ativar clientes;
Consulta de Acervo - Frontend;
Documentar visão de uso da solução.

<p><strong>Lições Aprendidas</strong></p>

Devido a dificuldades na ferramenta de scaffolding utilizado inicialmente, optamos por utilizar uma plataforma mais robusta utilizando Spring boot + Angular (jhipster). Tivemos algumas dificuldades na atualização da arquitetura com heroku ja existente para a nova arquitetura, tendo que recriar grande parte da aplicação para conseguir realizar o deploy.
