### ISSUE TITLE
** Documentação/Medição dos atributos de qualidade da aplicação **

### ISSUE THREAD

**Issue by estrazulas** [MprofSC/videolocadoraimperial#39]
- [x] Testabilidade
- [x] Segurança
- [x] Auditoria

.Testabilidade:
	Conforme metodologia definida, a testabilidade é um requisito de qualidade importante para o escopo do projeto, em que os principais casos de uso devem ter testes escritos antes da codificação e garantir que as novas funcionalidades não alterem negativamente o comportamento das funcionalidades ja em produção. Métrica: O sistema deve possuir 80% de cobertura de testes, e pode ser verificado através do plugin EclEmma do Eclipse.
	Prioridade Alta.

.Segurança:
	Nível de aceitação de segurança: A aplicação deverá ter controle de acesso para funcionalidades diferenciando por perfis de usuário, utilizando autenticação própria com logs de acesso. 
	Métrica: realizar uma autenticação com sucesso  e não permitir entrar em areas protegidas conforme regras de negócio.
	Prioridade Média.

.Auditoria:
	O sistema deve permitir auditoria dentre as operações critícas no sistema, de forma a indentificar as operações executadas e os usuários que realizaram tais açoes.
	Métrica: Executar alguma operação no sistema, como login por exemplo, verificando se apresenta os registros de usuário e data da operação.
	Prioridade Baixa.

**Comment by samuelbl** [comment]
.Testabilidade: 80% de cobertura nos testes, medição realizada com Eclemma/jacoco
![vlimperial](https://user-images.githubusercontent.com/5563783/52610015-107de380-2e5e-11e9-9081-3edb1bd5db9f.png)


.Auditoria: Log de login com usuário admin.
![auditorias](https://user-images.githubusercontent.com/5563783/52608921-35705780-2e5a-11e9-8a40-5dee3a32144e.png)

.Segurança: Acesso com usuário 'user', não exibindo as opções restritas a usuários administradores
![video locadora imperial](https://user-images.githubusercontent.com/5563783/52609020-9009b380-2e5a-11e9-81e8-57f54745ad47.png)
