### ISSUE TITLE
**Post Mortem - Iteração 5**

### ISSUE THREAD

**Issue by estrazulas** [MprofSC/videolocadoraimperial#45]
Resumo do que funcionou e do que não funcionou durante a execução da iteração, e planos para melhorar o que não funcionou, lições aprendidas, etc. 

Período: 24/01 - 02/02

- [x] O que estava planejado? atividades e pra quem
- [x] O que foi feito? atividades e por quem
- [x] O que não foi feito? atividades e por quem, quais os impedimentos
- [x] O que está planejado para a próxima iteração? atividades e pra quem
- [x]  Lições aprendidas (Post Mortem / Rationale)

**Comment by EliandroMinski** [comment]
# VIDEOLOCADORA IMPERIAL
<p> </p>
<p><strong>Postmortem</strong></p>
<table>
<thead>
<tr>
<th>Início da Interação</th>
<th>Término da Interação</th>
</tr>
</thead>
<tbody>
<tr>
<td>24/01/2018</td>
<td>02/02/2019</td>
</tbody>
</table>
<p> </p>
<p><strong>O Que Foi Planejado</strong></p>

Implementar cadastro de locações;
Implementação da reserva de itens;
Documentar visão de implantação;
Documentar funcionalidades e diferenciais;
Criar arquivo Postmortem.

<p><strong>O Que Foi Feito</strong></p>

Implementado cadastro de locações - Daniel; 
Implementado da reserva de itens - Samuel;
Documentado visão de implantação - Daniel;
Documentado funcionalidades e diferenciais - Samuel
Criado arquivo Postmortem - Eliandro.


<p><strong>O Que Não Foi Feito:</strong></p>

Todas as atividades planejadas foram concluídas.

<p><strong>Planejado Para a Próxima Interação:</strong></p>
