### ISSUE TITLE
**Implementar CRUD - Clientes**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#7]
- [x] Criar campos:  nome,  email,  endereço,  telefone  residencial, local onde trabalha, telefone comercial, telefone celular, sexo, CPF e data de nascimento
- [x] Criar classes de modelo
- [x] Criar classe de controle
- [x] Criar telas de cadastro, edição e consulta

**Comment by estrazulas** [comment]
#36 Fechado com pullrequest do branch com jhipster
