### ISSUE TITLE
**Implementar CRUD - cadastro de filmes**

### ISSUE THREAD

**Issue by samuelbl** [MprofSC/videolocadoraimperial#8]
- [x] Criar campos: título original, título em português, países, ano, direção, elenco, sinopse, duração e gênero.
- [x] Criar classes de modelo
- [x] Criar classe de controle
- [x] Criar telas de cadastro, edição e consulta

**Comment by estrazulas** [comment]
#36 Fechado com pullrequest do branch com jhipster
